# Site settings
title: Weedman Dan
description: A blog about Weedman Dan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://weedmandan.com" # the base hostname & protocol for your site 

# User settings
username: Weedman Dan
user_description: The king of weed
user_title: Weed Smoker
email: drosar33@gmail.com
disqus_username: weedmandan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
